version: "3.5"
services:
  sequencer:
    build:
      context: sequencer
      args:
        UPSTREAM_VERSION: v1.2.1
        DATA_DIRECTORY: /data
    volumes:
      - sequencer-data:/data
    environment:
      COINBASE: ""
      VALIDATOR_PRIVATE_KEY: ""
      BLOB_SINK_URL: ""
      SEQ_MIN_TX_BLOCK: ""
      SEQ_MAX_TX_BLOCK: ""
    restart: unless-stopped
  register:
    build:
      context: register
      args:
        UPSTREAM_VERSION: v1.2.1
    environment:
      VALIDATOR_PRIVATE_KEY: ""
      COINBASE: ""
    restart: "no"
volumes:
  sequencer-data: {}
